server:
  port: 8080
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - 'http://localhost:3000'
            allowed-headers:
              - '*'
            allowed-methods:
              - "GET"
              - "POST"
              - "PATCH"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
              - "HEAD"
            allow-credentials: true
      routes:
        - id: author
          uri: lb://author
          predicates:
            - Path=/v1/author/**
        - id: main
          uri: lb://main
          predicates:
            - Path=/v1/**
  application:
    name: gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    eureka-service-url-poll-interval-seconds: 10

auth:
  excludedPaths:
    - /v1/auth/login
    - /v1/auth/register
    - /v1/echo/**
    - /get
